
package org.nepostoji.paymentservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-09-09T22:48:39.191+02:00
 * Generated source version: 2.6.5
 * 
 */
 
public class PaymentService_PaymentPort_Server{

    protected PaymentService_PaymentPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new PaymentServiceImpl();
        String address = "http://localhost:8080/PaymentPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new PaymentService_PaymentPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
