
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.nepostoji.paymentservice;

import java.util.logging.Logger;

import org.example.nalogzaplacanje.NalogZaPlacanje;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-09-09T22:48:39.161+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "PaymentService",
                      portName = "PaymentPort",
                      targetNamespace = "http://www.nepostoji.org/PaymentService/",
                      wsdlLocation = "file:/D:/Users/Stevan/Literatura_I_Materijal/Aktuelno/XML_i_WS/Projekat/XML-WS-projekat/XMLWS/WEB-INF/wsdl/PaymentService.wsdl",
                      endpointInterface = "org.nepostoji.paymentservice.PaymentService")
                      
public class PaymentServiceImpl implements PaymentService {

    private static final Logger LOG = Logger.getLogger(PaymentServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see org.nepostoji.paymentservice.PaymentService#obradiNalog(org.nepostoji.paymentservice.PorukaNalogaPlacanja  parameters )*
     */
    public org.nepostoji.paymentservice.Odgovor obradiNalog(PorukaNalogaPlacanja parameters) { 
        LOG.info("Executing operation obradiNalog");
        System.out.println(parameters);
        try {
        	NalogZaPlacanje nalog = parameters.getNalog();
        	
        	
        		
        		
            org.nepostoji.paymentservice.Odgovor _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.nepostoji.paymentservice.PaymentService#prikaziPresjek(org.nepostoji.paymentservice.PorukaZahtijevaPresjeka  parameters )*
     */
    public org.nepostoji.paymentservice.PorukaPresjeka prikaziPresjek(PorukaZahtijevaPresjeka parameters) throws PrikaziPresjekFault    { 
        LOG.info("Executing operation prikaziPresjek");
        System.out.println(parameters);
        try {
            org.nepostoji.paymentservice.PorukaPresjeka _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PrikaziPresjekFault("prikaziPresjekFault...");
    }

    /* (non-Javadoc)
     * @see org.nepostoji.paymentservice.PaymentService#pokreniClearing(org.nepostoji.paymentservice.PogonskaPoruka  parameters )*
     */
    public org.nepostoji.paymentservice.Odgovor pokreniClearing(PogonskaPoruka parameters) { 
        LOG.info("Executing operation pokreniClearing");
        System.out.println("Poruka: " + parameters.getPoruka());
        try {
            org.nepostoji.paymentservice.Odgovor _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.nepostoji.paymentservice.PaymentService#odobriSredstvaClearing(org.nepostoji.paymentservice.PorukaOdobrenjaClearing  parameters )*
     */
    public org.nepostoji.paymentservice.Odgovor odobriSredstvaClearing(PorukaOdobrenjaClearing parameters) { 
        LOG.info("Executing operation odobriSredstvaClearing");
        System.out.println(parameters);
        try {
            org.nepostoji.paymentservice.Odgovor _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.nepostoji.paymentservice.PaymentService#odobriSredstvaRtgs(org.nepostoji.paymentservice.PorukaOdobrenjaRtgs  parameters )*
     */
    public org.nepostoji.paymentservice.Odgovor odobriSredstvaRtgs(PorukaOdobrenjaRtgs parameters) { 
        LOG.info("Executing operation odobriSredstvaRtgs");
        System.out.println(parameters);
        try {
            org.nepostoji.paymentservice.Odgovor _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
