
package org.nepostoji.paymentservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-09-09T22:48:39.076+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class PaymentService_PaymentPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.nepostoji.org/PaymentService/", "PaymentService");

    private PaymentService_PaymentPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PaymentService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PaymentService_Service ss = new PaymentService_Service(wsdlURL, SERVICE_NAME);
        PaymentService port = ss.getPaymentPort();  
        
        {
        System.out.println("Invoking obradiNalog...");
        org.nepostoji.paymentservice.PorukaNalogaPlacanja _obradiNalog_parameters = null;
        org.nepostoji.paymentservice.Odgovor _obradiNalog__return = port.obradiNalog(_obradiNalog_parameters);
        System.out.println("obradiNalog.result=" + _obradiNalog__return);


        }
        {
        System.out.println("Invoking prikaziPresjek...");
        org.nepostoji.paymentservice.PorukaZahtijevaPresjeka _prikaziPresjek_parameters = null;
        try {
            org.nepostoji.paymentservice.PorukaPresjeka _prikaziPresjek__return = port.prikaziPresjek(_prikaziPresjek_parameters);
            System.out.println("prikaziPresjek.result=" + _prikaziPresjek__return);

        } catch (PrikaziPresjekFault e) { 
            System.out.println("Expected exception: prikaziPresjekFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking pokreniClearing...");
        org.nepostoji.paymentservice.PogonskaPoruka _pokreniClearing_parameters = null;
        org.nepostoji.paymentservice.Odgovor _pokreniClearing__return = port.pokreniClearing(_pokreniClearing_parameters);
        System.out.println("pokreniClearing.result=" + _pokreniClearing__return);


        }
        {
        System.out.println("Invoking odobriSredstvaClearing...");
        org.nepostoji.paymentservice.PorukaOdobrenjaClearing _odobriSredstvaClearing_parameters = null;
        org.nepostoji.paymentservice.Odgovor _odobriSredstvaClearing__return = port.odobriSredstvaClearing(_odobriSredstvaClearing_parameters);
        System.out.println("odobriSredstvaClearing.result=" + _odobriSredstvaClearing__return);


        }
        {
        System.out.println("Invoking odobriSredstvaRtgs...");
        org.nepostoji.paymentservice.PorukaOdobrenjaRtgs _odobriSredstvaRtgs_parameters = null;
        org.nepostoji.paymentservice.Odgovor _odobriSredstvaRtgs__return = port.odobriSredstvaRtgs(_odobriSredstvaRtgs_parameters);
        System.out.println("odobriSredstvaRtgs.result=" + _odobriSredstvaRtgs__return);


        }

        System.exit(0);
    }

}
