package org.nepostoji.paymentservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-09-09T22:48:39.183+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.nepostoji.org/PaymentService/", name = "PaymentService")
@XmlSeeAlso({org.example.odgovor.ObjectFactory.class, org.example.mt103.ObjectFactory.class, org.example.mt102.ObjectFactory.class, org.example.mt910.ObjectFactory.class, org.example.zahtijevzaizvodom.ObjectFactory.class, ObjectFactory.class, org.example.presjek.ObjectFactory.class, org.example.nalogzaplacanje.ObjectFactory.class, org.example.mt9xx.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PaymentService {

    @WebMethod
    @WebResult(name = "odgovor", targetNamespace = "http://www.nepostoji.org/PaymentService/", partName = "parameters")
    public Odgovor obradiNalog(
        @WebParam(partName = "parameters", name = "obradiNalog", targetNamespace = "http://www.nepostoji.org/PaymentService/")
        PorukaNalogaPlacanja parameters
    );

    @WebMethod
    @WebResult(name = "prikaziPresjekResponse", targetNamespace = "http://www.nepostoji.org/PaymentService/", partName = "parameters")
    public PorukaPresjeka prikaziPresjek(
        @WebParam(partName = "parameters", name = "prikaziPresjek", targetNamespace = "http://www.nepostoji.org/PaymentService/")
        PorukaZahtijevaPresjeka parameters
    ) throws PrikaziPresjekFault;

    @WebMethod
    @WebResult(name = "odgovor", targetNamespace = "http://www.nepostoji.org/PaymentService/", partName = "parameters")
    public Odgovor pokreniClearing(
        @WebParam(partName = "parameters", name = "pogonskaPoruka", targetNamespace = "http://www.nepostoji.org/PaymentService/")
        PogonskaPoruka parameters
    );

    @WebMethod
    @WebResult(name = "odgovor", targetNamespace = "http://www.nepostoji.org/PaymentService/", partName = "parameters")
    public Odgovor odobriSredstvaClearing(
        @WebParam(partName = "parameters", name = "odobriSredstvaClearing", targetNamespace = "http://www.nepostoji.org/PaymentService/")
        PorukaOdobrenjaClearing parameters
    );

    @WebMethod
    @WebResult(name = "odgovor", targetNamespace = "http://www.nepostoji.org/PaymentService/", partName = "parameters")
    public Odgovor odobriSredstvaRtgs(
        @WebParam(partName = "parameters", name = "odobriSredstvaRtgs", targetNamespace = "http://www.nepostoji.org/PaymentService/")
        PorukaOdobrenjaRtgs parameters
    );
}
