
package org.nepostoji.paymentservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-09-09T22:48:39.153+02:00
 * Generated source version: 2.6.5
 */

@WebFault(name = "odgovor", targetNamespace = "http://www.nepostoji.org/PaymentService/")
public class PrikaziPresjekFault extends Exception {
    
    private org.nepostoji.paymentservice.Odgovor odgovor;

    public PrikaziPresjekFault() {
        super();
    }
    
    public PrikaziPresjekFault(String message) {
        super(message);
    }
    
    public PrikaziPresjekFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PrikaziPresjekFault(String message, org.nepostoji.paymentservice.Odgovor odgovor) {
        super(message);
        this.odgovor = odgovor;
    }

    public PrikaziPresjekFault(String message, org.nepostoji.paymentservice.Odgovor odgovor, Throwable cause) {
        super(message, cause);
        this.odgovor = odgovor;
    }

    public org.nepostoji.paymentservice.Odgovor getFaultInfo() {
        return this.odgovor;
    }
}
