
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.nepostoji.centralbankingservice;

import java.util.concurrent.ConcurrentHashMap;
import java.util.logging.Logger;

import org.example.mt103.MT103;

import model.ObracunskiRacun;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-09-09T22:48:42.511+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "CentralBankingService",
                      portName = "CentralBankingServicePort",
                      targetNamespace = "http://www.nepostoji.org/CentralBankingService/",
                      wsdlLocation = "file:/D:/Users/Stevan/Literatura_I_Materijal/Aktuelno/XML_i_WS/Projekat/XML-WS-projekat/XMLWS/WEB-INF/wsdl/CentralBankingService.wsdl",
                      endpointInterface = "org.nepostoji.centralbankingservice.CentralBankingService")
                      
public class CentralBankingServiceImpl implements CentralBankingService {
	private ConcurrentHashMap<String, ObracunskiRacun> obracunskiRacuni = new ConcurrentHashMap<String, ObracunskiRacun>();
    private static final Logger LOG = Logger.getLogger(CentralBankingServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see org.nepostoji.centralbankingservice.CentralBankingService#rtgs(org.nepostoji.centralbankingservice.Rtgs  parameters )*
     */
    public org.nepostoji.centralbankingservice.Zaduzenje rtgs(Rtgs parameters) throws FaultResponse    { 
        LOG.info("Executing operation rtgs");
        System.out.println(parameters);
        try {
            org.nepostoji.centralbankingservice.Zaduzenje _return = null;
            MT103 mt103 = parameters.getMt103();
        	ObracunskiRacun duznickiRacun = obracunskiRacuni.get(mt103.getObracunskiRacunBankeDuznika());
        	ObracunskiRacun primaocevRacun = obracunskiRacuni.get(mt103.getObracunskiRacunBankePrimaoca());
        	if(duznickiRacun==null) {
        		
        	}
        	if(primaocevRacun==null) {
        		
        	}
        	if(duznickiRacun.getStanje().compareTo(mt103.getIznos()) < 0) {
        		
        	}
        	
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultResponse("faultResponse...");
    }

    /* (non-Javadoc)
     * @see org.nepostoji.centralbankingservice.CentralBankingService#clearing(org.nepostoji.centralbankingservice.Clearing  parameters )*
     */
    public org.nepostoji.centralbankingservice.Zaduzenje clearing(Clearing parameters) throws FaultResponse    { 
        LOG.info("Executing operation clearing");
        System.out.println(parameters);
        try {
            org.nepostoji.centralbankingservice.Zaduzenje _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FaultResponse("faultResponse...");
    }

}
