package org.nepostoji.centralbankingservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-09-09T22:48:42.528+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.nepostoji.org/CentralBankingService/", name = "CentralBankingService")
@XmlSeeAlso({org.example.odgovor.ObjectFactory.class, org.example.mt103.ObjectFactory.class, org.example.mt102.ObjectFactory.class, ObjectFactory.class, org.example.mt900.ObjectFactory.class, org.example.mt9xx.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CentralBankingService {

    @WebMethod
    @WebResult(name = "poruka_o_zaduzenju", targetNamespace = "http://www.nepostoji.org/CentralBankingService/", partName = "parameters")
    public Zaduzenje rtgs(
        @WebParam(partName = "parameters", name = "rtgs", targetNamespace = "http://www.nepostoji.org/CentralBankingService/")
        Rtgs parameters
    ) throws FaultResponse;

    @WebMethod
    @WebResult(name = "poruka_o_zaduzenju", targetNamespace = "http://www.nepostoji.org/CentralBankingService/", partName = "parameters")
    public Zaduzenje clearing(
        @WebParam(partName = "parameters", name = "clearing", targetNamespace = "http://www.nepostoji.org/CentralBankingService/")
        Clearing parameters
    ) throws FaultResponse;
}
