
package org.nepostoji.centralbankingservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-09-09T22:48:42.422+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class CentralBankingService_CentralBankingServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.nepostoji.org/CentralBankingService/", "CentralBankingService");

    private CentralBankingService_CentralBankingServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CentralBankingService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CentralBankingService_Service ss = new CentralBankingService_Service(wsdlURL, SERVICE_NAME);
        CentralBankingService port = ss.getCentralBankingServicePort();  
        
        {
        System.out.println("Invoking rtgs...");
        org.nepostoji.centralbankingservice.Rtgs _rtgs_parameters = null;
        try {
            org.nepostoji.centralbankingservice.Zaduzenje _rtgs__return = port.rtgs(_rtgs_parameters);
            System.out.println("rtgs.result=" + _rtgs__return);

        } catch (FaultResponse e) { 
            System.out.println("Expected exception: faultResponse has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking clearing...");
        org.nepostoji.centralbankingservice.Clearing _clearing_parameters = null;
        try {
            org.nepostoji.centralbankingservice.Zaduzenje _clearing__return = port.clearing(_clearing_parameters);
            System.out.println("clearing.result=" + _clearing__return);

        } catch (FaultResponse e) { 
            System.out.println("Expected exception: faultResponse has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
